# TCL File Generated by Component Editor 18.1
# Wed Jul 09 23:19:07 BRT 2025
# DO NOT MODIFY


# 
# background_loader "background_loader" v1.0
#  2025.07.09.23:19:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module background_loader
# 
set_module_property DESCRIPTION ""
set_module_property NAME background_loader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_component
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME background_loader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL background_loader
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file background_loader.v VERILOG PATH sources/background_loader.v TOP_LEVEL_FILE
add_fileset_file master_interface.v VERILOG PATH sources/master_interface.v
add_fileset_file fifo_background.vhd VHDL PATH fifo_background.vhd

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL background_loader
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file background_loader.v VERILOG PATH sources/background_loader.v
add_fileset_file master_interface.v VERILOG PATH sources/master_interface.v
add_fileset_file fifo_background.vhd VHDL PATH fifo_background.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_address address Input 8
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master waitrequest waitrequest Input 1
add_interface_port master readdatavalid readdatavalid Input 1
add_interface_port master readdata readdata Input 32
add_interface_port master read read Output 1
add_interface_port master chipselect chipselect Output 1
add_interface_port master byteenable byteenable Output 4
add_interface_port master address address Output 30
add_interface_port master burstcount burstcount Output 5
add_interface_port master beginbursttransfer beginbursttransfer Output 1


# 
# connection point fifo_bg_data
# 
add_interface fifo_bg_data conduit end
set_interface_property fifo_bg_data associatedClock clock
set_interface_property fifo_bg_data associatedReset reset
set_interface_property fifo_bg_data ENABLED true
set_interface_property fifo_bg_data EXPORT_OF ""
set_interface_property fifo_bg_data PORT_NAME_MAP ""
set_interface_property fifo_bg_data CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_data SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_data exportdata fifo_bg_data Output 24


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit pll_locked pll_locked Input 1


# 
# connection point fifo_bg_rd_en
# 
add_interface fifo_bg_rd_en conduit end
set_interface_property fifo_bg_rd_en associatedClock clock
set_interface_property fifo_bg_rd_en associatedReset reset
set_interface_property fifo_bg_rd_en ENABLED true
set_interface_property fifo_bg_rd_en EXPORT_OF ""
set_interface_property fifo_bg_rd_en PORT_NAME_MAP ""
set_interface_property fifo_bg_rd_en CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_rd_en SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_rd_en fifo_rd_en fifo_bg_rd_en Input 1


# 
# connection point fifo_bg_empty
# 
add_interface fifo_bg_empty conduit end
set_interface_property fifo_bg_empty associatedClock clock
set_interface_property fifo_bg_empty associatedReset reset
set_interface_property fifo_bg_empty ENABLED true
set_interface_property fifo_bg_empty EXPORT_OF ""
set_interface_property fifo_bg_empty PORT_NAME_MAP ""
set_interface_property fifo_bg_empty CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_empty SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_empty bg_fifo_empty fifo_bg_empty Output 1


# 
# connection point bg_fifo_full
# 
add_interface bg_fifo_full conduit end
set_interface_property bg_fifo_full associatedClock clock
set_interface_property bg_fifo_full associatedReset reset
set_interface_property bg_fifo_full ENABLED true
set_interface_property bg_fifo_full EXPORT_OF ""
set_interface_property bg_fifo_full PORT_NAME_MAP ""
set_interface_property bg_fifo_full CMSIS_SVD_VARIABLES ""
set_interface_property bg_fifo_full SVD_ADDRESS_GROUP ""

add_interface_port bg_fifo_full bg_fifo_full bg_fifo_full Output 1

