# TCL File Generated by Component Editor 18.1
# Mon Jul 14 11:19:12 BRT 2025
# DO NOT MODIFY


# 
# composer "composer" v1.0
#  2025.07.14.11:19:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module composer
# 
set_module_property DESCRIPTION ""
set_module_property NAME composer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_component
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME composer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL composer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file composer.v VERILOG PATH sources/composer.v TOP_LEVEL_FILE
add_fileset_file background_fifo_reader.v VERILOG PATH sources/background_fifo_reader.v
add_fileset_file pixel_composer.v VERILOG PATH sources/pixel_composer.v
add_fileset_file pixel_counter.v VERILOG PATH sources/pixel_counter.v
add_fileset_file sprite_pixel_fetcher.v VERILOG PATH sources/sprite_pixel_fetcher.v
add_fileset_file sprite_visibility_checker.v VERILOG PATH sources/sprite_visibility_checker.v
add_fileset_file top4_sprite_selector.v VERILOG PATH sources/top4_sprite_selector.v
add_fileset_file composer_ctrl.v VERILOG PATH sources/composer_ctrl.v
add_fileset_file border_analyzer.v VERILOG PATH sources/border_analyzer.v
add_fileset_file collision_sprite_analyzer.v VERILOG PATH sources/collision_sprite_analyzer.v
add_fileset_file rom_sprites.vhd VHDL PATH rom_sprites.vhd

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL composer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file composer.v VERILOG PATH sources/composer.v
add_fileset_file background_fifo_reader.v VERILOG PATH sources/background_fifo_reader.v
add_fileset_file pixel_composer.v VERILOG PATH sources/pixel_composer.v
add_fileset_file pixel_counter.v VERILOG PATH sources/pixel_counter.v
add_fileset_file sprite_pixel_fetcher.v VERILOG PATH sources/sprite_pixel_fetcher.v
add_fileset_file sprite_visibility_checker.v VERILOG PATH sources/sprite_visibility_checker.v
add_fileset_file top4_sprite_selector.v VERILOG PATH sources/top4_sprite_selector.v
add_fileset_file composer_ctrl.v VERILOG PATH sources/composer_ctrl.v
add_fileset_file rgb16_to_rgb24.v VERILOG PATH sources/rgb16_to_rgb24.v
add_fileset_file border_analyzer.v VERILOG PATH sources/border_analyzer.v
add_fileset_file collision_sprite_analyzer.v VERILOG PATH sources/collision_sprite_analyzer.v
add_fileset_file rom_sprites.vhd VHDL PATH rom_sprites.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon
# 
add_interface avalon avalon end
set_interface_property avalon addressUnits WORDS
set_interface_property avalon associatedClock clock
set_interface_property avalon associatedReset reset_n
set_interface_property avalon bitsPerSymbol 8
set_interface_property avalon burstOnBurstBoundariesOnly false
set_interface_property avalon burstcountUnits WORDS
set_interface_property avalon explicitAddressSpan 0
set_interface_property avalon holdTime 0
set_interface_property avalon linewrapBursts false
set_interface_property avalon maximumPendingReadTransactions 0
set_interface_property avalon maximumPendingWriteTransactions 0
set_interface_property avalon readLatency 0
set_interface_property avalon readWaitTime 1
set_interface_property avalon setupTime 0
set_interface_property avalon timingUnits Cycles
set_interface_property avalon writeWaitTime 0
set_interface_property avalon ENABLED true
set_interface_property avalon EXPORT_OF ""
set_interface_property avalon PORT_NAME_MAP ""
set_interface_property avalon CMSIS_SVD_VARIABLES ""
set_interface_property avalon SVD_ADDRESS_GROUP ""

add_interface_port avalon avalon_write write Input 1
add_interface_port avalon avalon_address address Input 8
add_interface_port avalon avalon_writedata writedata Input 32
set_interface_assignment avalon embeddedsw.configuration.isFlash 0
set_interface_assignment avalon embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset_n
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit pixel_out pixel_out Output 24
add_interface_port conduit wrfull wrfull Input 1
add_interface_port conduit wrreq wrreq Output 1
add_interface_port conduit new_frame_test new_frame_test Output 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1


# 
# connection point fifo_bg_data
# 
add_interface fifo_bg_data conduit end
set_interface_property fifo_bg_data associatedClock clock
set_interface_property fifo_bg_data associatedReset reset_n
set_interface_property fifo_bg_data ENABLED true
set_interface_property fifo_bg_data EXPORT_OF ""
set_interface_property fifo_bg_data PORT_NAME_MAP ""
set_interface_property fifo_bg_data CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_data SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_data bg_fifo_q fifo_bg_data Input 24


# 
# connection point fifo_bg_empty
# 
add_interface fifo_bg_empty conduit end
set_interface_property fifo_bg_empty associatedClock clock
set_interface_property fifo_bg_empty associatedReset reset_n
set_interface_property fifo_bg_empty ENABLED true
set_interface_property fifo_bg_empty EXPORT_OF ""
set_interface_property fifo_bg_empty PORT_NAME_MAP ""
set_interface_property fifo_bg_empty CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_empty SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_empty bg_fifo_empty fifo_bg_empty Input 1


# 
# connection point fifo_bg_rd_en
# 
add_interface fifo_bg_rd_en conduit end
set_interface_property fifo_bg_rd_en associatedClock clock
set_interface_property fifo_bg_rd_en associatedReset reset_n
set_interface_property fifo_bg_rd_en ENABLED true
set_interface_property fifo_bg_rd_en EXPORT_OF ""
set_interface_property fifo_bg_rd_en PORT_NAME_MAP ""
set_interface_property fifo_bg_rd_en CMSIS_SVD_VARIABLES ""
set_interface_property fifo_bg_rd_en SVD_ADDRESS_GROUP ""

add_interface_port fifo_bg_rd_en bg_fifo_rdreq fifo_bg_rd_en Output 1


# 
# connection point bg_fifo_full
# 
add_interface bg_fifo_full conduit end
set_interface_property bg_fifo_full associatedClock clock
set_interface_property bg_fifo_full associatedReset reset_n
set_interface_property bg_fifo_full ENABLED true
set_interface_property bg_fifo_full EXPORT_OF ""
set_interface_property bg_fifo_full PORT_NAME_MAP ""
set_interface_property bg_fifo_full CMSIS_SVD_VARIABLES ""
set_interface_property bg_fifo_full SVD_ADDRESS_GROUP ""

add_interface_port bg_fifo_full bg_fifo_full bg_fifo_full Input 1

