// SistemaEmbarcado_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module SistemaEmbarcado_mm_interconnect_0 (
		input  wire        clock_clk_clk,                                        //                                      clock_clk.clk
		input  wire        ProcessadorCentral_reset_reset_bridge_in_reset_reset, // ProcessadorCentral_reset_reset_bridge_in_reset.reset
		input  wire [31:0] ProcessadorCentral_data_master_address,               //                 ProcessadorCentral_data_master.address
		output wire        ProcessadorCentral_data_master_waitrequest,           //                                               .waitrequest
		input  wire        ProcessadorCentral_data_master_read,                  //                                               .read
		output wire [31:0] ProcessadorCentral_data_master_readdata,              //                                               .readdata
		input  wire        ProcessadorCentral_data_master_write,                 //                                               .write
		input  wire [31:0] ProcessadorCentral_data_master_writedata,             //                                               .writedata
		output wire [9:0]  RAM_s1_address,                                       //                                         RAM_s1.address
		output wire        RAM_s1_write,                                         //                                               .write
		input  wire [31:0] RAM_s1_readdata,                                      //                                               .readdata
		output wire [31:0] RAM_s1_writedata,                                     //                                               .writedata
		output wire [3:0]  RAM_s1_byteenable,                                    //                                               .byteenable
		output wire        RAM_s1_chipselect,                                    //                                               .chipselect
		output wire        RAM_s1_clken                                          //                                               .clken
	);

	wire         processadorcentral_data_master_translator_avalon_universal_master_0_waitrequest;   // RAM_s1_translator:uav_waitrequest -> ProcessadorCentral_data_master_translator:uav_waitrequest
	wire  [31:0] processadorcentral_data_master_translator_avalon_universal_master_0_readdata;      // RAM_s1_translator:uav_readdata -> ProcessadorCentral_data_master_translator:uav_readdata
	wire         processadorcentral_data_master_translator_avalon_universal_master_0_debugaccess;   // ProcessadorCentral_data_master_translator:uav_debugaccess -> RAM_s1_translator:uav_debugaccess
	wire  [31:0] processadorcentral_data_master_translator_avalon_universal_master_0_address;       // ProcessadorCentral_data_master_translator:uav_address -> RAM_s1_translator:uav_address
	wire         processadorcentral_data_master_translator_avalon_universal_master_0_read;          // ProcessadorCentral_data_master_translator:uav_read -> RAM_s1_translator:uav_read
	wire   [3:0] processadorcentral_data_master_translator_avalon_universal_master_0_byteenable;    // ProcessadorCentral_data_master_translator:uav_byteenable -> RAM_s1_translator:uav_byteenable
	wire         processadorcentral_data_master_translator_avalon_universal_master_0_readdatavalid; // RAM_s1_translator:uav_readdatavalid -> ProcessadorCentral_data_master_translator:uav_readdatavalid
	wire         processadorcentral_data_master_translator_avalon_universal_master_0_lock;          // ProcessadorCentral_data_master_translator:uav_lock -> RAM_s1_translator:uav_lock
	wire         processadorcentral_data_master_translator_avalon_universal_master_0_write;         // ProcessadorCentral_data_master_translator:uav_write -> RAM_s1_translator:uav_write
	wire  [31:0] processadorcentral_data_master_translator_avalon_universal_master_0_writedata;     // ProcessadorCentral_data_master_translator:uav_writedata -> RAM_s1_translator:uav_writedata
	wire   [2:0] processadorcentral_data_master_translator_avalon_universal_master_0_burstcount;    // ProcessadorCentral_data_master_translator:uav_burstcount -> RAM_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) processadorcentral_data_master_translator (
		.clk                    (clock_clk_clk),                                                                     //                       clk.clk
		.reset                  (ProcessadorCentral_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (processadorcentral_data_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (processadorcentral_data_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (processadorcentral_data_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (processadorcentral_data_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (processadorcentral_data_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (processadorcentral_data_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (processadorcentral_data_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (processadorcentral_data_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (processadorcentral_data_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (processadorcentral_data_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (processadorcentral_data_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (ProcessadorCentral_data_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (ProcessadorCentral_data_master_waitrequest),                                        //                          .waitrequest
		.av_read                (ProcessadorCentral_data_master_read),                                               //                          .read
		.av_readdata            (ProcessadorCentral_data_master_readdata),                                           //                          .readdata
		.av_write               (ProcessadorCentral_data_master_write),                                              //                          .write
		.av_writedata           (ProcessadorCentral_data_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                              //               (terminated)
		.av_byteenable          (4'b1111),                                                                           //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                              //               (terminated)
		.av_begintransfer       (1'b0),                                                                              //               (terminated)
		.av_chipselect          (1'b0),                                                                              //               (terminated)
		.av_readdatavalid       (),                                                                                  //               (terminated)
		.av_lock                (1'b0),                                                                              //               (terminated)
		.av_debugaccess         (1'b0),                                                                              //               (terminated)
		.uav_clken              (),                                                                                  //               (terminated)
		.av_clken               (1'b1),                                                                              //               (terminated)
		.uav_response           (2'b00),                                                                             //               (terminated)
		.av_response            (),                                                                                  //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                              //               (terminated)
		.av_writeresponsevalid  ()                                                                                   //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ram_s1_translator (
		.clk                    (clock_clk_clk),                                                                     //                      clk.clk
		.reset                  (ProcessadorCentral_reset_reset_bridge_in_reset_reset),                              //                    reset.reset
		.uav_address            (processadorcentral_data_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (processadorcentral_data_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (processadorcentral_data_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (processadorcentral_data_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (processadorcentral_data_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (processadorcentral_data_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (processadorcentral_data_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (processadorcentral_data_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (processadorcentral_data_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (processadorcentral_data_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (processadorcentral_data_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (RAM_s1_address),                                                                    //      avalon_anti_slave_0.address
		.av_write               (RAM_s1_write),                                                                      //                         .write
		.av_readdata            (RAM_s1_readdata),                                                                   //                         .readdata
		.av_writedata           (RAM_s1_writedata),                                                                  //                         .writedata
		.av_byteenable          (RAM_s1_byteenable),                                                                 //                         .byteenable
		.av_chipselect          (RAM_s1_chipselect),                                                                 //                         .chipselect
		.av_clken               (RAM_s1_clken),                                                                      //                         .clken
		.av_read                (),                                                                                  //              (terminated)
		.av_begintransfer       (),                                                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                                                  //              (terminated)
		.av_burstcount          (),                                                                                  //              (terminated)
		.av_readdatavalid       (1'b0),                                                                              //              (terminated)
		.av_waitrequest         (1'b0),                                                                              //              (terminated)
		.av_writebyteenable     (),                                                                                  //              (terminated)
		.av_lock                (),                                                                                  //              (terminated)
		.uav_clken              (1'b0),                                                                              //              (terminated)
		.av_debugaccess         (),                                                                                  //              (terminated)
		.av_outputenable        (),                                                                                  //              (terminated)
		.uav_response           (),                                                                                  //              (terminated)
		.av_response            (2'b00),                                                                             //              (terminated)
		.uav_writeresponsevalid (),                                                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                               //              (terminated)
	);

endmodule
