# TCL File Generated by Component Editor 18.1
# Tue Jun 03 20:23:33 BRT 2025
# DO NOT MODIFY


# 
# ProcessadorCentral "ProcessadorCentral" v1.1
#  2025.06.03.20:23:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ProcessadorCentral
# 
set_module_property DESCRIPTION ""
set_module_property NAME ProcessadorCentral
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Meus Componentes"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ProcessadorCentral
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CPU
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CPU.v VERILOG PATH CPU.v TOP_LEVEL_FILE
add_fileset_file ALU.v VERILOG PATH ALU.v
add_fileset_file ALUControl.v VERILOG PATH ALUControl.v
add_fileset_file AvalonMM_Master_DataInterface.v VERILOG PATH AvalonMM_Master_DataInterface.v
add_fileset_file AvalonMM_Master_InstInterface.v VERILOG PATH AvalonMM_Master_InstInterface.v
add_fileset_file Control.v VERILOG PATH Control.v
add_fileset_file EX_STAGE.v VERILOG PATH EX_STAGE.v
add_fileset_file ForwardingUnit.v VERILOG PATH ForwardingUnit.v
add_fileset_file HazardDetectionUnit.v VERILOG PATH HazardDetectionUnit.v
add_fileset_file ID_STAGE.v VERILOG PATH ID_STAGE.v
add_fileset_file IF_STAGE.v VERILOG PATH IF_STAGE.v
add_fileset_file MEM_STAGE.v VERILOG PATH MEM_STAGE.v
add_fileset_file PLL.vhd VHDL PATH PLL.vhd
add_fileset_file RegFile.v VERILOG PATH RegFile.v
add_fileset_file ResetSync.v VERILOG PATH ResetSync.v
add_fileset_file WB_STAGE.v VERILOG PATH WB_STAGE.v
add_fileset_file MemoryStallUnit.v VERILOG PATH MemoryStallUnit.v
add_fileset_file Avalon_Interruption_Interface.bsf OTHER PATH Avalon_Interruption_Interface.bsf

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CPU
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CPU.v VERILOG PATH CPU.v
add_fileset_file ALU.v VERILOG PATH ALU.v
add_fileset_file ALUControl.v VERILOG PATH ALUControl.v
add_fileset_file AvalonMM_Master_DataInterface.v VERILOG PATH AvalonMM_Master_DataInterface.v
add_fileset_file AvalonMM_Master_InstInterface.v VERILOG PATH AvalonMM_Master_InstInterface.v
add_fileset_file Control.v VERILOG PATH Control.v
add_fileset_file EX_STAGE.v VERILOG PATH EX_STAGE.v
add_fileset_file ForwardingUnit.v VERILOG PATH ForwardingUnit.v
add_fileset_file HazardDetectionUnit.v VERILOG PATH HazardDetectionUnit.v
add_fileset_file ID_STAGE.v VERILOG PATH ID_STAGE.v
add_fileset_file IF_STAGE.v VERILOG PATH IF_STAGE.v
add_fileset_file MEM_STAGE.v VERILOG PATH MEM_STAGE.v
add_fileset_file PLL.vhd VHDL PATH PLL.vhd
add_fileset_file RegFile.v VERILOG PATH RegFile.v
add_fileset_file ResetSync.v VERILOG PATH ResetSync.v
add_fileset_file WB_STAGE.v VERILOG PATH WB_STAGE.v
add_fileset_file MemoryStallUnit.v VERILOG PATH MemoryStallUnit.v
add_fileset_file Avalon_Interruption_Interface.bsf OTHER PATH Avalon_Interruption_Interface.bsf


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point data_master
# 
add_interface data_master avalon start
set_interface_property data_master addressUnits SYMBOLS
set_interface_property data_master associatedClock clock
set_interface_property data_master associatedReset reset
set_interface_property data_master bitsPerSymbol 8
set_interface_property data_master burstOnBurstBoundariesOnly false
set_interface_property data_master burstcountUnits WORDS
set_interface_property data_master doStreamReads false
set_interface_property data_master doStreamWrites false
set_interface_property data_master holdTime 0
set_interface_property data_master linewrapBursts false
set_interface_property data_master maximumPendingReadTransactions 0
set_interface_property data_master maximumPendingWriteTransactions 0
set_interface_property data_master readLatency 0
set_interface_property data_master readWaitTime 1
set_interface_property data_master setupTime 0
set_interface_property data_master timingUnits Cycles
set_interface_property data_master writeWaitTime 0
set_interface_property data_master ENABLED true
set_interface_property data_master EXPORT_OF ""
set_interface_property data_master PORT_NAME_MAP ""
set_interface_property data_master CMSIS_SVD_VARIABLES ""
set_interface_property data_master SVD_ADDRESS_GROUP ""

add_interface_port data_master d_waitrequest waitrequest Input 1
add_interface_port data_master d_readdata readdata Input 32
add_interface_port data_master d_read read Output 1
add_interface_port data_master d_write write Output 1
add_interface_port data_master d_address address Output 32
add_interface_port data_master d_writedata writedata Output 32


# 
# connection point instruction_master
# 
add_interface instruction_master avalon start
set_interface_property instruction_master addressUnits SYMBOLS
set_interface_property instruction_master associatedClock clock
set_interface_property instruction_master associatedReset reset
set_interface_property instruction_master bitsPerSymbol 8
set_interface_property instruction_master burstOnBurstBoundariesOnly false
set_interface_property instruction_master burstcountUnits WORDS
set_interface_property instruction_master doStreamReads false
set_interface_property instruction_master doStreamWrites false
set_interface_property instruction_master holdTime 0
set_interface_property instruction_master linewrapBursts false
set_interface_property instruction_master maximumPendingReadTransactions 0
set_interface_property instruction_master maximumPendingWriteTransactions 0
set_interface_property instruction_master readLatency 0
set_interface_property instruction_master readWaitTime 1
set_interface_property instruction_master setupTime 0
set_interface_property instruction_master timingUnits Cycles
set_interface_property instruction_master writeWaitTime 0
set_interface_property instruction_master ENABLED true
set_interface_property instruction_master EXPORT_OF ""
set_interface_property instruction_master PORT_NAME_MAP ""
set_interface_property instruction_master CMSIS_SVD_VARIABLES ""
set_interface_property instruction_master SVD_ADDRESS_GROUP ""

add_interface_port instruction_master i_address address Output 32
add_interface_port instruction_master i_read read Output 1
add_interface_port instruction_master i_readdata readdata Input 32
add_interface_port instruction_master i_waitrequest waitrequest Input 1


# 
# connection point iterruption
# 
add_interface iterruption avalon end
set_interface_property iterruption addressUnits WORDS
set_interface_property iterruption associatedClock clock
set_interface_property iterruption associatedReset reset
set_interface_property iterruption bitsPerSymbol 8
set_interface_property iterruption burstOnBurstBoundariesOnly false
set_interface_property iterruption burstcountUnits WORDS
set_interface_property iterruption explicitAddressSpan 0
set_interface_property iterruption holdTime 0
set_interface_property iterruption linewrapBursts false
set_interface_property iterruption maximumPendingReadTransactions 0
set_interface_property iterruption maximumPendingWriteTransactions 0
set_interface_property iterruption readLatency 0
set_interface_property iterruption readWaitTime 1
set_interface_property iterruption setupTime 0
set_interface_property iterruption timingUnits Cycles
set_interface_property iterruption writeWaitTime 0
set_interface_property iterruption ENABLED true
set_interface_property iterruption EXPORT_OF ""
set_interface_property iterruption PORT_NAME_MAP ""
set_interface_property iterruption CMSIS_SVD_VARIABLES ""
set_interface_property iterruption SVD_ADDRESS_GROUP ""

add_interface_port iterruption interrupt write Input 1
add_interface_port iterruption interrupt_data writedata Input 32
add_interface_port iterruption realized waitrequest Output 1
add_interface_port iterruption realized_data readdata Output 32
set_interface_assignment iterruption embeddedsw.configuration.isFlash 0
set_interface_assignment iterruption embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment iterruption embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment iterruption embeddedsw.configuration.isPrintableDevice 0

